### ISSUE TITLE
Add 'Star this repo' button

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#12]
Add a 'star this repo' button in the footer of the site.

**Comment by Amarjit-Khan** [comment]
Hey, can I solve this issue?

**Comment by pexeixv** [comment]
Assign me this issue and I will fix it under Hacktoberfest.

**Comment by pexeixv** [comment]
Also, congratulations on winning #1 at Dennis Ivy's hackathon. I won #5. 😉

**Comment by mittal-parth** [comment]
Hi @Amarjit-Khan, @pexeixv since @Amarjit-Khan requested first. I'll allow him to go ahead and try to solve it. 
If he is unable to do so in the next 7 days, I'll assign it to @pexeixv 😄

**Comment by pexeixv** [comment]
No issues @mittal-parth

**Comment by mittal-parth** [comment]
Thank you so much @pexeixv! ✨ 
Congratulations to you too! I really liked your colour scheme! 💙
