### ISSUE TITLE
Change <a> tags to markdown style

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#16]
In the readme, replace all <a> tags with the markdown style of using []()

**Comment by Anubhakri13** [comment]
Hey Mittal, May i work on this?

**Comment by mittal-parth** [comment]
Yes please go ahead!

**Comment by shivansh12032004** [comment]
Is this issue still open to work on?

**Comment by mittal-parth** [comment]
Hi @shivansh12032004, this is assigned to @Anubhakri13. I have assigned #3 to you! 😄

**Comment by Anubhakri13** [comment]
> Is this issue still open to work on?
> 

I am working on this
