### ISSUE TITLE
Make name on Hero and Footer section dynamic

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#17]
The name of the person is hard coded in the Hero.jsx [component](https://github.com/mittal-parth/personal-portfolio/blob/main/src/components/Hero.jsx#L41) and Footer [component](https://github.com/mittal-parth/personal-portfolio/blob/main/src/components/Footer.jsx#L13)
Change it to be dynamic by fetching it from [`/src/constants/index.js`](https://github.com/mittal-parth/personal-portfolio/blob/main/src/constants/index.js)

**Comment by Pranav4399** [comment]
I can work on this

**Comment by mittal-parth** [comment]
@Pranav4399 Sure go ahead.

**Comment by GustavoGomesRibeiro** [comment]
@mittal-parth Please assign me.

**Comment by Eli4479** [comment]
assign it to me i can make the text dynamic with a cursor going to and fro

**Comment by mittal-parth** [comment]
@Pranav4399 are you still working on this?

**Comment by Pranav4399** [comment]
@mittal-parth Apologies. I haven't started working on this yet. Please assign it to anyone else in case they're interested.

**Comment by mittal-parth** [comment]
@Pranav4399 thanks for the clarification. 
Assigned to @GustavoGomesRibeiro
