### ISSUE TITLE
Add dynamic Call to Action

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#18]
The 'LetsConnect' component has my linkedin hardcoded at [line 8](https://github.com/mittal-parth/personal-portfolio/blob/main/src/components/LetsConnect.jsx#L8)

Change it to dynamically fetch from [`/src/constants/index.js`](https://github.com/mittal-parth/personal-portfolio/blob/main/src/constants/index.js). This can be done by: 
Create a new constant called `callToAction` in the [`/src/constants/index.js`](https://github.com/mittal-parth/personal-portfolio/blob/main/src/constants/index.js) file and use this instead of the hardcoded LinkedIn URL

**Comment by asamaiya00** [comment]
Hi @mittal-parth , may I work on this? Please assign it to me.

**Comment by mittal-parth** [comment]
Hi @asamaiya00 sure. Assigned!
