### ISSUE TITLE
Increase footer padding on tablets

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#24]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/76661350/193448339-f349ac09-1631-466a-8a57-1f6de2de47ca.png">

The left padding on the footer for the tablet viewport is too less. Add padding on the left only for tablets.

**Comment by Ahnaf-codes** [comment]
I can do it @mittal-parth

**Comment by mittal-parth** [comment]
@Ahnaf-codes go ahead. Assigned!

**Comment by utkarsh2709** [comment]
Hello @mittal-parth, I can do the following task and can help you in improving UI even further.

**Comment by mittal-parth** [comment]
Hi @utkarsh2709! I'm sorry but its already been assigned.
If you have any other issues/ideas you can go ahead and make an issue and we can look into that. Thanks!

**Comment by codeboyfriend** [comment]
I can help in adding animation nd typewriting effect to the it

Kindly assigned this to me
