### ISSUE TITLE
Irregular footer width

### ISSUE THREAD

**Issue by pexeixv** [mittal-parth/personal-portfolio#26]
The entire site is contained in a max-width of 1280px, however, the footer is not. This breaks the flow of the site and makes it look unusual.
If you feel this is a valid issue, please assign it to me and I will fix it under Hacktoberfest.

![image](https://user-images.githubusercontent.com/68476117/193460552-afeedcdf-c8cb-442b-841d-7633b8bd8181.png)

**Comment by mittal-parth** [comment]
@pexeixv nice catch! Assigned to you!
