### ISSUE TITLE
Projects: Add name of tech stack on hover.

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#3]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/76661350/193418900-35bfb7ef-e1fd-47c5-a2f6-8de85d8768df.png">

When hovering over the tech stack icons in the projects (like JS here), the name of the technology can be displayed.

**Comment by shivansh12032004** [comment]
hey, can I work on this issue?

**Comment by mittal-parth** [comment]
Hi, @shivansh12032004, please go ahead!

**Comment by Eli4479** [comment]
i can also work here. we can also pop the hovered tech-stack.with its name being display

**Comment by AhmdFarzki** [comment]
Hey @mittal-parth, I've been trying to do it, is this what you want? Please assign to me.

![Screenshot (86)](https://user-images.githubusercontent.com/54702541/193549057-f77a0d3f-8719-42f3-baaa-03ba3226486b.png)

**Comment by mittal-parth** [comment]
Hi @shivansh12032004 are you still working on this?

**Comment by AhmdFarzki** [comment]
@mittal-parth please check my pull request #33

**Comment by mittal-parth** [comment]
Assigned to @AhmdFarzki.
