### ISSUE TITLE
Footer: Make tagline dynamic

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#31]
Similar to #17, The tagline of the person is hard coded in the  Footer [component](https://github.com/mittal-parth/personal-portfolio/blob/main/src/components/Footer.jsx#L13)
Change it to be dynamic by fetching it from [`/src/constants/index.js`](https://github.com/mittal-parth/personal-portfolio/blob/main/src/constants/index.js)

**Comment by mittal-parth** [comment]
@Eli4479 would you like to work on this?

**Comment by Ritesh-Dabral** [comment]
@mittal-parth
Hi, I would like to work on this issue.

**Comment by mittal-parth** [comment]
Assigned to @Ritesh-Dabral.
