### ISSUE TITLE
Footer: Add credit notes

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#35]
Add a line _Made with 💙 by Parth Mittal & the Open Source Community_ at the end of the footer separated by a line.

**Comment by isurumaldeniya** [comment]
@mittal-parth Hi can I work on this?

**Comment by mittal-parth** [comment]
@isurumaldeniya go ahead!

**Comment by isurumaldeniya** [comment]
@mittal-parth Hi I added a PR. Please review it and let me know if anything needed to be changed.
