### ISSUE TITLE
Achievements: Fix carousel on mobile devices

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#56]
The arrows scroll the cards more than the phone width making it difficult to read. 

The arrows should scroll correctly on mobile (one card at a time) and bigger devices (2/3 cards at a time).

**Comment by Sapna127** [comment]
hey, I would like work on this issue. Please assign it to me. 

just to confirm you are talking about this problem only, right ?
![image](https://github.com/user-attachments/assets/2865310d-1685-4282-accd-25a4f4c02722)

**Comment by mittal-parth** [comment]
Hi @Sapna127!

Yes, there should be one card visible at a time on mobile. Right now, some of the 1st card is cut and some of the second card is visible. 

For bigger devices, 2-3 cards should be visible at a time (which is the case right now)

Assigned, thanks!
