### ISSUE TITLE
Enhancement: Smoothen the animations

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#61]
The currently used animation library is Framer Motion - https://www.framer.com/motion/

Although its great, I often feel that the animations jitter - they arent butter smooth. 

So either play around with the delays, configs etc of framer wherever its being used.

OR

I am open to moving away from this library and using some other library like React Spring or GSAP. But if we are doing this, I would like to see this implemented in the existing design and only then move.

**Comment by A-4-Atom** [comment]
Hi, I've previously used framer motion in one of my projects. Assign this issue to me, I can try improving the animations. 
If it doesn't work we can figure out something else. 
@mittal-parth

**Comment by mittal-parth** [comment]
Hi @A-4-Atom!
Thanks, go ahead!
