### ISSUE TITLE
Misc: Cleanup the React warnings

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#66]
There are some warnings generated on the console right now:

- [ ] Warning: ForwardRef: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.
- [x] Warning: Each child in a list should have a unique "key" prop (4 times)
- [x] Warning: Invalid DOM property `class`. Did you mean `className`?
- [x] Warning: validateDOMNesting(...): `<div> cannot appear as a descendant of <p>`.
- [x] Warning: <AiFillGithub /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.

Please fix these. Some are pretty straightforward. The last one might require some debugging.

**Comment by SureshPradhana** [comment]
I'd like to work on this

**Comment by mittal-parth** [comment]
Assigned @SureshPradhana! :)

**Comment by Nitheesh-2003** [comment]
Hi there,
Can I work on this please?

**Comment by mittal-parth** [comment]
Hi @Nitheesh-2003, go ahead! :)

**Comment by Nitheesh-2003** [comment]
hey any specific action to reproduce the issue?
Because when I execute the code these warnings are not shown there 

![image](https://github.com/user-attachments/assets/b22b983a-1aeb-41b8-88ce-fe763d9987da)

**Comment by Nitheesh-2003** [comment]
Okay I got in the browser console
