### ISSUE TITLE
Docs: Add instructions about GitHub API

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#70]
After the recent merge of #65, we need to do the following:

- Remove the hard coded open source contributions from [`/src/constants/index.js`](https://github.com/mittal-parth/personal-portfolio/blob/main/src/constants/index.js#L490) and its imports across the project (if any)
- Alter the readme to add instructions on adding an environment variable as mentioned in the .env.example file.
- Also mention add steps/link(s) to obtain the GitHub API token.

**Comment by Karan-Brar** [comment]
Hi, I would like to work on this issue. I am new to open source contribution, so I might reach out if i feel unsure!

**Comment by Karan-Brar** [comment]
Thanks! I am almost done working on this issue, a quick question - in the readme file should I talk about modifying the 'includedRepos' constant so that 'Open Source Contributions' section that uses the API token correctly reflects a users contributions?

**Comment by mittal-parth** [comment]
Hey, lets do one thing.

The readme mentions the [constants/index](https://github.com/mittal-parth/personal-portfolio/blob/main/src/constants/index.js) file as a whole. We can edit this constants file itself and add more comments explaining wherever required.

Add comments at the beginning of each section like 'Open Source Contributions or Education'.

And any more comments if required (like for included repos).

This will keep the readme clean and help the user while editing the constants file itself.

**Comment by Karan-Brar** [comment]
Sounds like a good idea, I will make the changes and create a PR shortly

**Comment by Karan-Brar** [comment]
Created PR for review!
