### ISSUE TITLE
Add loading screen animation

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/personal-portfolio#8]
Add an animation when the website loads for the first time.
Ideally, the icon displayed should be the one used at the website title - [icon](https://github.com/mittal-parth/personal-portfolio/blob/main/src/assets/parth.svg)

**Comment by asamaiya00** [comment]
Hi @mittal-parth, may I work on this? Please assign it to me.

**Comment by programmerraja** [comment]
can you assign to me @mittal-parth

**Comment by mittal-parth** [comment]
Sure go ahead. Please put a screen recording in the PR.

**Comment by programmerraja** [comment]
Sure
